# Generated by Django 6.0.2 on 2026-07-27 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0002_alter_favorite_author_categories_delete_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["title", "author"],
                include=("rating",),
                name="idx_favorite_title_author_cover",
            ),
        ),
    ]
